language: ruby
rvm:
- 2.4.1
services:
- postgresql
bundler_args: "--without production --jobs=3"
cache: bundler
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- cp config/database-travis.yml config/database.yml
- bundle exec rake db:schema:load RAILS_ENV=test
notifications:
  slack:
    secure: QFzPJAW7ApuCSDlOy752bJ4FWUgGZSNFQgx/RALlVBRnyflOLiSJbfQCavpxbjtblpjHRCGW0w2QtF9GBAOOZIbSbmQim2j/+WNI1OKFNb1eCxgyF9cFJt1yePI1faYzz4nODoxG3JKYmBxfAWynw4B7ymg1GA4Rrw2QTlO8+FJ2mL1ofeMDcVrtaPQV6lbfQ9shb2ggeszBHh5KPYZr1F1pOGm7BmoupuOYAKKm4vF1g7nIb0AqoaCrIbPxrifjllycKKBDqMa34arObC2Z4KE9djIgF47qUg3BzM6rm8KDsA2zUoULlv7TVCSKIXw9jrhjRF44CtoQsuHNL5P8vdohoVSqryTNCpN6vjpLrew1/GvcCAi5eyTfD5hDC4xNYKB7BuOi7f90x6gd5uc7D6+ULTOJFkB7GHmc4mKXddgzXx2ivg96QfXRIGfp7ba//dIEcwuQNuBrBeAIz+qby1j7dROsgQ8i2GZ9dyMSKKXWbkGzMzh5MxkRvqq8cb3vvLCZnafqzh4FDd0CiJMwAf5aaprAjefzkzIcq1LSkEgznP0YGSshXrnLzluAzZJntCWqp9rFk+SiUZXWR7wwohkthFnmTUqWw4JdVX33ojRoCNUyE/K7i3GWMA9lmtkClFizdGv0o+whXNkWkvsyNN1BnLqM4fxTCBQAF4nTGKw=
deploy:
  provider: heroku
  api_key:
    secure: XuN7g5p9lCn3I56oCKZjaMTXuLsuTktpJ46XrvGsbdkWEBm01HNmroBkU5tZ9vVmuDysEYv1MA/wKSD1FsL+LzVLGoYuF8+v3JN0wENs+9yLpwPJV/KPCZbp1gg9puCHSl9EU2cSLIm0lfOWdKJisyk9ggAj6Xs9dRsdx+LHno5E6l67taRrpKqa4H+PXO36dBd/fUPeFUn2Ieu8eYsynZHTInEPoYHPqBL4XsMe+ztLrNo07jUHa39LcW2WnWvgYyySGPOqF7+ajxPAgLmlBRIM9w/5KSEbK+tdRHNr+U85VJkqXXHP4XiSTasWIsC+6BAd4kjBcQCYcyix5uLpjYWMmkZj6XdoS/Zhj+owfa+1IkdQK8Ump4ia+nnKiW2s1iR209mU4NR5uWfnSqtYe5PhaJxYkaRjItyItl1q3IucmY2gHLP2+idE+Foqk7bgZ4nMDknFWKbmSDaGQ7MJeUrASA+zFQuEULw19yF0kXYfcYr3dPoXsQg97Rs5cDP8QLlv0upArA4n4/4xM35O/xFPRHMFruDtqXzQQ/H9PFlvKBgRQhs1UzFE5H6d4v5xPa7UTAYIvespAPUxYr73S9w4icD9Qg3EIdji4Vc1BFhTvhJk8+/l4XJRqvptRUqwk3V7NaCk2Hi7xy647D1L17BUmmUU7HbRJP8iAo5xFKU=
  run: rake db:migrate
  app:
    master: techladies-mvs
