dist: trusty
addons:
  chrome: stable
language: ruby
rvm:
- 2.5.3
services:
- postgresql
bundler_args: "--without production --jobs=3"
cache: bundler
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- cp config/database-travis.yml config/database.yml
- bundle exec rake db:schema:load RAILS_ENV=test
notifications:
  slack:
    secure: QFzPJAW7ApuCSDlOy752bJ4FWUgGZSNFQgx/RALlVBRnyflOLiSJbfQCavpxbjtblpjHRCGW0w2QtF9GBAOOZIbSbmQim2j/+WNI1OKFNb1eCxgyF9cFJt1yePI1faYzz4nODoxG3JKYmBxfAWynw4B7ymg1GA4Rrw2QTlO8+FJ2mL1ofeMDcVrtaPQV6lbfQ9shb2ggeszBHh5KPYZr1F1pOGm7BmoupuOYAKKm4vF1g7nIb0AqoaCrIbPxrifjllycKKBDqMa34arObC2Z4KE9djIgF47qUg3BzM6rm8KDsA2zUoULlv7TVCSKIXw9jrhjRF44CtoQsuHNL5P8vdohoVSqryTNCpN6vjpLrew1/GvcCAi5eyTfD5hDC4xNYKB7BuOi7f90x6gd5uc7D6+ULTOJFkB7GHmc4mKXddgzXx2ivg96QfXRIGfp7ba//dIEcwuQNuBrBeAIz+qby1j7dROsgQ8i2GZ9dyMSKKXWbkGzMzh5MxkRvqq8cb3vvLCZnafqzh4FDd0CiJMwAf5aaprAjefzkzIcq1LSkEgznP0YGSshXrnLzluAzZJntCWqp9rFk+SiUZXWR7wwohkthFnmTUqWw4JdVX33ojRoCNUyE/K7i3GWMA9lmtkClFizdGv0o+whXNkWkvsyNN1BnLqM4fxTCBQAF4nTGKw=
deploy:
  provider: heroku
  api_key:
    secure: TRqatDei8zPKpXyB1NQQh3PtGKd/p90aXtyhhXcv8dIhHPw1rv44GKMeVsJxUMGXoq7QFLcoItuW8B+khyqo5OAyy2G/V/NaN11HajachbvvU43Nl2Bhz8CTnpgqMLKjs9gBqX0FggfWNJBw7HkI+Pq6i1hfWgzu0a50P1BNzQ0B538AQ1D5I1erICRGELphPlIWq1zV+gxhbbmNQKS0Dj6TpTQ4O6XJkV46Hyrdp1u7aFdQRzY8kyXjs6unwCAUlbbJTXz+izppjkM9EKvZjMABC6W6W6epCoSnwpVJZ2t1GJSVjJGgjc/GXdm8aX56ZSKooMnCKg/EJohsknvdrgeQSK6HAgV5FYeXbkCH4a7BvVchR0DeMDSp/um+OxHBbuFbqYqlrbPukgt4/oBNsYYFpOn9UN5RONfsCb3kfu5ZKAThTqSWp6i0VO7ZovKNHrycgnr5nEqnr3eEsdyNDXuCWVZ76ESsxsAbhK8J3FVUoHiLRUSB9MVWWWkDKFYXJ6Owx/nZJxzWE710Di4dovgQj3Um/k65sCljc1u3x0Lxm+X7mG14NYeoH9BLUEIOzhAxG9pre2yWE1vb9fKbfHNJmbYubdKV6dy3eS5alzdSQ2Sxadvg0Y87WpjTzhQxl3iERIpTcJBgESN9xaHaG6SfOfBLsLozHxORlGq0dkA=
  run: rake db:migrate
  app:
    master: techladies-mvs
